### ISSUE TITLE
Не хватает лимита данных в полях

### ISSUE THREAD

**Issue by Anisan** [sergejey/majordomo-zigbeedev#1]
https://github.com/sergejey/majordomo-zigbeedev/blob/846574b641be76caad7db85d61d9975019862d63/modules/zigbeedev/zigbeedev.class.php#L588
кроме этого в коде нет проверки на NULL, происходят попытки записи NULL в поля к которых задано not null

**Comment by sergejey** [comment]
про null понял, но насчёт лимита что имеется в виду? пытается записать больше 255 символов и падает с ошибкой?

**Comment by Anisan** [comment]
да, при попытке записи цикл падает. И таких данных много, особенно у (HUB)
