### ISSUE TITLE
список неподдерживаемых устройств выеденных по ссылке "check for unsupported devices"

### ISSUE THREAD

**Issue by NickNeoOne** [sergejey/majordomo-zigbeedev#14]
[
    {
        "MODEL": "MFKZQ01LM",
        "MODEL_NAME": "lumi.sensor_cube.aqgl01",
        "PROPERTIES": [
            {
                "TITLE": "action:wakeup",
                "VALUE": "2023-08-14 21:51:57"
            },
            {
                "TITLE": "action",
                "VALUE": "tap",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "status"
            },
            {
                "TITLE": "battery",
                "VALUE": "100",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "batteryLevel"
            },
            {
                "TITLE": "current",
                "VALUE": "0"
            },
            {
                "TITLE": "device_temperature",
                "VALUE": "25",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "temperature"
            },
            {
                "TITLE": "last_seen",
                "VALUE": "2023-08-17T06:42:48.661Z"
            },
            {
                "TITLE": "linkquality",
                "VALUE": "78"
            },
            {
                "TITLE": "power",
                "VALUE": "4193"
            },
            {
                "TITLE": "power_outage_count",
                "VALUE": "624"
            },
            {
                "TITLE": "side",
                "VALUE": "5",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "side"
            },
            {
                "TITLE": "voltage",
                "VALUE": "3005"
            },
            {
                "TITLE": "action:rotate_left",
                "VALUE": "2023-08-17 10:42:27",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "rotate_left"
            },
            {
                "TITLE": "action_angle",
                "VALUE": "103.84",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "action_rotation"
            },
            {
                "TITLE": "action:flip90",
                "VALUE": "2023-08-17 10:42:19",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "flip90"
            },
            {
                "TITLE": "action_from_side",
                "VALUE": "3"
            },
            {
                "TITLE": "action_side",
                "VALUE": "5"
            },
            {
                "TITLE": "action_to_side",
                "VALUE": "5"
            },
            {
                "TITLE": "action:rotate_right",
                "VALUE": "2023-08-17 10:42:31",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "rotate_right"
            },
            {
                "TITLE": "action:shake",
                "VALUE": "2023-08-17 10:16:34",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "action_shake"
            },
            {
                "TITLE": "availability",
                "VALUE": "online",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "alive"
            },
            {
                "TITLE": "action:fall",
                "VALUE": "2023-08-14 22:02:25",
                "LINKED_OBJECT": "AllScripts",
                "LINKED_METHOD": "Yandex \u043f\u043e\u0434\u0431\u0440\u043e\u0441\u0438\u0442\u044c \u043a\u0443\u0431\u0438\u043a"
            },
            {
                "TITLE": "action:flip180",
                "VALUE": "2023-08-14 22:01:06",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "flip180"
            },
            {
                "TITLE": "action:slide",
                "VALUE": "2023-08-17 10:42:05",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "action_slide"
            },
            {
                "TITLE": "action:tap",
                "VALUE": "2023-08-17 10:42:48",
                "LINKED_OBJECT": "Cube01",
                "LINKED_PROPERTY": "action_tap"
            }
        ]
    },
    {
        "MODEL": "SNZB-01",
        "MODEL_NAME": "WB01",
        "PROPERTIES": [
            {
                "TITLE": "availability",
                "VALUE": "online"
            },
            {
                "TITLE": "battery",
                "VALUE": "90"
            },
            {
                "TITLE": "last_seen",
                "VALUE": "2023-07-27T19:52:00.501Z"
            },
            {
                "TITLE": "linkquality",
                "VALUE": "66"
            },
            {
                "TITLE": "voltage",
                "VALUE": "2900"
            },
            {
                "TITLE": "action:single",
                "VALUE": "2023-07-17 09:24:08",
                "LINKED_OBJECT": "Relay16 (device type: relay)",
                "LINKED_METHOD": "switch"
            },
            {
                "TITLE": "action",
                "VALUE": "single"
            },
            {
                "TITLE": "action:double",
                "VALUE": "2023-01-28 21:16:06"
            },
            {
                "TITLE": "action:long",
                "VALUE": "2022-10-28 19:48:56"
            }
        ]
    }
]

PS: у кубика гораздо больше вариантов действий чем отображается в модуле, у себя сделал (возможно криво) при изменению "action" выполняется метод который создает дополнительные топики в mqtt(например: если повернуть кубик на стороне 5 то создастся топик вида: cube/rotate_left/side-5/set), а к ним я  уже привязываю какое либо ПУ

**Comment by NickNeoOne** [comment]
было бы неплохо, если это можно было сделать как-то в модуле zigbeedev без написания методов вручную.

**Comment by sergejey** [comment]
Насчёт action -- при каждом новом действии создаётся свойство с типом действия (например "action:double") -- и на него уже можно привязывать необходимую реакцию. Или речь о чём-то другом?

**Comment by sergejey** [comment]
Кубик добавлен в известные устройства.

**Comment by NickNeoOne** [comment]
> Насчёт action -- при каждом новом действии создаётся свойство с типом действия (например "action:double") -- и на него уже можно привязывать необходимую реакцию. Или речь о чём-то другом?

Да действия создаются, но они создаются без учета стороны на которой сделано данное действие.
То есть повернули куб влево, создалось свойство "action:rotate_left" но у куба 6 сторон и поворот на каждой из них можно привязать к разным действиям.
Было бы более функционально,  чтобы создавалось вот по такому типу: "action:действие:**_сторона_куба_**", например куб находится стороной 3 вверх повернули налево создалось "action:rotate_left:**_side_3_**"

PS: я пробовал привязывать метод к свойству "action:какое_либо_действие" и проверять свойство "action_side" или "side" с помощью "getGlobal('Cube01.action_side')" ('Cube01.side') чтобы реализовать различные действия в зависимости от стороны куба, но почему-то свойство "action_side(side)" не обновляется если куб перевернули и получает предыдущее значение, хотя в самом модуле оно обновляется. В общем как то странно оно работает, не особо понял в чем причина, в качестве варианта попробовал через создание метода в объекте, например при повороте:

при изменении свойства "action_rotation" метод создает топики в mqtt 

```
$action = $this->getProperty('status');
$action_rotation = $this->getProperty('action_rotation');
$side = $this->getProperty('side');
if ($action != 'wakeup') {
//  say(implode('', array('Произведено действие: ',$action,' на стороне: ',$side)), 2);
callAPI('/api/module/mqtt','GET',array('publish'=>'cube/'.$action.'/side-'.$side.'/set','msg'=>"1"));
callAPI('/api/module/mqtt','GET',array('publish'=>'cube/'.$action.'/side-'.$side.'/action_rotation','msg'=>$action_rotation));
}
```

реализовано скорее всего криво и возможно есть более лучший вариант, но так вроде более менее адекватно работает (вращение, встряхивание, постукивание). 

там есть еще действия повороты на 90 и 180 на определенную сторону (повернули на 90 градусов на сторону 4) но они так и не заработали корректно (хотя они не особо нужны, так как запомнить потом будет сложно какой поворот за какое действие отвечает)
